language: python
python:
  - "3.5.2"
env:
  - DJANGO=1.8.4
install:
  - pip install -r requirements.txt
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - pyflakes -x W src
script:
  - python py.test