language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.8.4

before_install:
  - export DJANGO_SETTINGS_MODULE=hotlemon.settings
  - export PYTHONPATH=$HOME/builds/jooke42/HotLemon_serveur
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py syncdb --all
  - pytest