language: python
python:
  - "3.5.2"
env:
  - DJANGO=1.8.4
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
script:
  - py.test
after_success:
  - coveralls