language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r test_requirements.txt"
# command to run tests
script: pytest

after_success:
- pip freeze
- echo Uploading code coverage data ...; coveralls
- echo Code complexity scores:; radon cc --min B ../pony-forum

notifications:
  email:
    on_success: change
    on_failure: always